### ISSUE TITLE
Add a screencast to README

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/debugme#7]

**Comment by nbenn** [comment]
Then where do those xxx MiB master lines come from (just out of curiosity)?

**Comment by gaborcsardi** [comment]
https://github.com/gaborcsardi/prompt#readme

**Comment by nbenn** [comment]
Interesting! Thanks! One more question (sorry for bugging you about this): where does the first line come from?

~/works/mango/shinytest master* 3m29s

The color scheme looks the same as in the R output, but the R session is only started afterwards.

**Comment by gaborcsardi** [comment]
zsh prompt: https://github.com/sindresorhus/pure

**Comment by nbenn** [comment]
Thanks!
